export interface Booking {
  bookingId?: number; // Optional, as it's generated by the backend
  userId: number;
  packageId: number;
  tripStartDate: string; // Match your package's date format
  tripEndDate: string; // Match your package's date format
  status: 'PENDING' | 'CONFIRMED' | 'CANCELLED'; // Or whatever statuses your backend uses
  insuranceId?: number; // Optional, if you integrate insurance selection
  paymentId?: number; // Optional, will be linked after payment
}